version: '3.8'
services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
    command: uvicorn api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
